services:
  elasticsearch:
    image: chuckcharlie/elasticsearch-nextcloud-docker-multiarch:latest
    container_name: elasticsearch_nc
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      # Disable authentication and ssl completely
      # - xpack.security.enabled=false
      # Use this to enable Basic Authentication:
      # - xpack.security.enabled=true
      # - xpack.security.http.ssl.enabled=false
      # - ELASTIC_PASSWORD=mySuperSecret
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # Use named volume because of permission problems
      - elasticsearch_data:/usr/share/elasticsearch/data 
    ports:
      - 127.0.0.1:9200:9200

volumes:
  elasticsearch_data:
